---
title: 'Homework #6'
author: "Hye Yun Oh"
date: "2018<eb>ÖÑ 4<ec>õî 17<ec>ùº"
output:
  word_document: default
  html_document: default
---

```{r message=F, warning=F}

#Part1 : Logistic Regression 


##data

library(readxl)
has<-read_excel("C:\\Users\\user\\Desktop\\Haskins-Default-100 (1).xls",col_names=TRUE,sheet=3)

##(a)

library(MASS)
library(ggplot2) 

mylogit<- glm(Y~R1+R2+R3+R4+R5+R6+R7+R8+R9+R10+R11+R12+R13+R14+R15+R16+R17+R18+R19+R20+R21+R22+R23+R24,data=has,family=binomial(link = "logit"))
aic_has<-stepAIC(mylogit,direction="backward",scope=list(lower=~R1,upper=~.),steps=25)
aic_p<-aic_has$anova$AIC
aic_p
qplot(aic_has$anova$Step,aic_p)       ###aic (step) 


###final model : Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22

##(b)

optlm<- glm(Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22,data=has,family=binomial(link = "logit"))
glm.prob<-predict(optlm,type="response")
length(which(glm.prob>.5))/length(glm.prob)           ###survival probability

##(c)

library(lmtest)
lrtest(optlm,mylogit)       

### pvalue: 0.8561   not reject h0


##(d)

library(gclus)
fit<-optlm$model
fit<-data.frame(fit)
head(fit)
library(car)
library(RColorBrewer)

my_colors<-brewer.pal(nlevels(as.factor(fit$Y)),"Set2")
scatterplotMatrix(~ R1 + R2 + R5,data=fit,groups=fit$Y,by.groups=TRUE,col=my_colors)       ###scatterplot of regression 
scatterplotMatrix(~ R6 + R9 + R11 ,data=fit,groups=fit$Y,by.groups=TRUE,col=my_colors)
scatterplotMatrix(~ R12 + R16 + R18 ,data=fit,groups=fit$Y,by.groups=TRUE,col=my_colors) 
scatterplotMatrix(~ + R21 + R22  ,data=fit,groups=fit$Y,by.groups=TRUE,col=my_colors)

two<-cbind(glm.prob[1:50],glm.prob[51:100])                   ### prediction probability data 
colnames(two)<-c("Y==0","Y==1")
head(two)
boxplot(two,main="Boxplot of Prediction",ylim=c(0,1.2))

plot(density(glm.prob[1:50]), main = "Bankrupt Companies")    ### Y==0  (bankrupt)
plot(density(glm.prob[51:100]),main = "Solvent Companies")    ### Y==1  (solvent)

##(e)

summary(optlm)$cov.unscaled                  ### covariance matrix
confint(optlm)                               ### confidence interval

##(f)

### reduced model 

n<-100
n01<-length(which(two[,1]>=.5))          ### reduced model  : solvent n01
n00<-length(which(two[,1]<.5))            ### reduced model   : solvent n00
n11<-length(which(two[,2]>=.5))          ### reduced model  : solvent n11
n10<-length(which(two[,2]<.5))            ### reduced model  : solvent n10

error.matrix<-matrix(c(n01,n00,n11,n10),nrow=2, ncol=2)
colnames(error.matrix)<-c("bankrupt","solvent")
rownames(error.matrix)<-c("bankrupt","solvent")
error.matrix                              ### reduced model matrix
tot.err<-(n10+n01)/n                      ###total misclassification error of reduced model 

### full model 

glm.prob.full<-predict(mylogit,type="response")
two.full<-cbind(glm.prob.full[1:50],glm.prob.full[51:100])                   ### full model probability data 
colnames(two.full)<-c("Y==0","Y==1")

n01.full<-length(which(two.full[,1]>=.5))          ### full model  : solvent n01
n00.full<-length(which(two.full[,1]<.5))            ### full model   : solvent n00
n11.full<-length(which(two.full[,2]>=.5))          ### full model  : solvent n11
n10.full<-length(which(two.full[,2]<.5))            ### full model  : solvent n10

error.matrix.full<-matrix(c(n01.full,n00.full,n11.full,n10.full),nrow=2, ncol=2)
colnames(error.matrix.full)<-c("bankrupt","solvent")
rownames(error.matrix.full)<-c("bankrupt","solvent")
error.matrix.full                             ### full model matrix
tot.err.full<-(n10.full+n01.full)/n                      ###total misclassification error of full model

c(tot.err,tot.err.full)
```
```{r message=F, warning=F}
#Part2 : Sensitivity Analysis for MLE

##(1)

library(MASS)
prof<-profile(optlm)

pf.plot.ftn<-function(prof,num){

disp<-attr(prof,"summary")$dispersion
mindev<-attr(prof,"original.fit")$deviance
a<-plot(prof[[num]][,1],-0.5*prof[[num]]$z^2*disp+mindev,type="b")
print(a);

}

pf.plot.ftn(prof,2)                ### b1
pfci<-confint(prof,level=0.9)            ### confindence interval for profile likelihood
pfci

##(2)

Formula <- Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22
coefs <- sapply(1:nrow(has), function(i)
  coef(glm(Formula, data=has[-i, ], family=binomial(link = "logit"))
))                                  ###betahat(i)
coefs

n<-ncol(coefs)

sum<-matrix(0,nrow=nrow(coefs))
for(i in 1: n){
sum<-sum+coefs[,i]
}
betaj<-as.matrix(sum/n)          ###betahaj
betaj


blank<-matrix(0,nrow=nrow(coefs),ncol=nrow(coefs))
for(i in 1: n){
blank<-blank+(coefs[,i]-betaj)%*%t((coefs[,i]-betaj))
}

varbj<-blank*(n-1)/n             ###varbj matrix
varbj

b<-matrix(0,nrow=nrow(coefs),ncol=2)

for(i in 1:nrow(b)){
b[i,]<-c(betaj[i]-sqrt(diag(varbj)[i]),betaj[i]+sqrt(diag(varbj)[i]))
}
b                                ###ci for betahaj

##(3)

library(bootstrap)

hasample1<-has
mu<-glm.prob
n <- nrow(has)
B <- 1000

for (b in 1:B) {
hasample1$Y<-rbinom(n,1,glm.prob)
bootGlm1 <- glm(Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22,data=hasample1,family=binomial(link = "logit"))
}
pbootci<-confint(bootGlm1,level=0.9)       ###confindence interval of paramatric Bootstrap
pbootci

for (b in 1:B) {
    i <- sample(n, n, replace = TRUE)
    bootGlm2 <- glm(Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22, family=binomial(link = "logit"), data = has[i, ])
}
nbootci<-confint(bootGlm2,level=0.9) [-1,]  ###confindence interval of non-paramatric Bootstrap
nbootci

##(4)

Formula <- Y ~ R1 + R2 + R5 + R6 + R9 + R11 + R12 + R16 + R18 + R21 + R22
n01.cv<-0
n00.cv<-0
n11.cv<-0
n10.cv<-0

prob.cv.0<-matrix(0,nrow=nrow(has)-1,ncol=nrow(has)/2)
for(i in 1:ncol(prob.cv.0)){
  prob.cv.0[,i]<-as.matrix(predict(glm(Formula, data=has[-i,], family=binomial(link = "logit")),type="response"))
     n01.cv<-n01.cv+sum(which(prob.cv.0[,i]>=.5)<=49)
     n00.cv<-n00.cv+sum(which(prob.cv.0[,i]<.5)<=49)
}
n01.cv<-n01.cv/50
n00.cv<-n00.cv/50

prob.cv.1<-matrix(0,nrow=nrow(has)-1,ncol=nrow(has)/2)
for(i in 1:ncol(prob.cv.1)){
  prob.cv.1[,i]<-as.matrix(predict(glm(Formula, data=has[-(i+nrow(has)/2),], family=binomial(link = "logit")),type="response"))
  n10.cv<-n10.cv+sum(which(prob.cv.1[,i]<.5)>=51)
  n11.cv<-n11.cv+sum(which(prob.cv.1[,i]>=.5)>=51)
}

n10.cv<-n10.cv/50
n11.cv<-n11.cv/50

tot.err.cv<-(n10.cv+n01.cv)/n         ###total misclassification error of full model
tot.err.cv                            ###smaller than the one of full model 
tot.err.full                                ###total misclassification error of full model
```