---
title: "Homework#7-Part2"
author: "Hye Yun Oh"
date: "2018³â 5¿ù 6ÀÏ"
output: html_document
---

```{r,warning=FALSE,message=FALSE}
#Part2 : Antoine equation 

##library

library(readxl)
library(tidyverse)
library(ggplot2)

##data manipulation

dat2<-read_excel("C:\\Users\\user\\Desktop\\APT-Antoine-Mark-Recapture data (2).xlsx",sheet=2)
colnames(dat2)<-c("celcius","T","p")
dat2<-mutate(dat2,lnp=log(as.numeric(p)),Tinv=1/as.numeric(T),p=p/100)

##scatter plot (a)

s1<-ggplot(data=dat2,aes(x=p,y=T))+geom_point(alpha=0.3)
s2<-ggplot(data=dat2,aes(x=lnp,y=T))+geom_point(alpha=0.3)
s3<-ggplot(data=dat2,aes(x=lnp,y=Tinv))+geom_point(alpha=0.3)
dev.off()           ### eliminating error

s1
s2
s3
```

```{r,warning=FALSE,message=FALSE}
##Estimation(b)
##simple linear model 

a<-rep(0,7)
b<-rep(0,7)

for( c in seq(-10,50,10))
{nlss<-nls(lnp~a+b/(T-c),start=list(a=0,b=0),data=dat2)
a[c/10+2]<-summary(nlss)$coefficients[1]
b[c/10+2]<-summary(nlss)$coefficients[2]
}

cbind("c"=seq(-10,50,10),a,b)    ###estimation of a, b,c

##Gauss Newton Algorithm

n<-13
dat2_1<-mutate(dat2,lnpT=lnp/T)
lm2<-lm(lnp~Tinv+lnpT,data=dat2_1)
summary(lm2)
alpha<-as.numeric(lm2$coefficients[1])  ###coefficients
beta<-as.numeric(lm2$coefficients[2])
gamma<-as.numeric(lm2$coefficients[3])

a0<-alpha                   ###initial value 
b0<-beta+alpha*gamma
c0<-gamma

g<-function(a,b,c,data){
  	 as.matrix(a+b/(data$T-c))
}

zf<-function(g,data){
   	data$lnp-g
}

m=100

af<-rep(0,m)
bf<-rep(0,m)
cf<-rep(0,m)
betaf<-matrix(0,0, nrow=3,ncol=m)

af[1]<-a0
bf[1]<-b0
cf[1]<-c0

for(i in 1:m){

z<-zf(g(af[i],bf[i],cf[i],dat2),dat2)
X<-cbind(rep(1,13),1/(dat2$T-cf[i]),bf[i]/(dat2$T-cf[i])^2)
X<-as.matrix(X)
betaf[,i]<-solve(t(X)%*%X)%*%t(X)%*%z  ###beta
af[i+1]<-af[i]+betaf[1,i]  ###theta
bf[i+1]<-bf[i]+betaf[2,i] 
cf[i+1]<-cf[i]+betaf[3,i]
}
af[100]         ###convergence
bf[100]
cf[100]

var<-sum(dat2$lnp-g(af,bf,cf,dat2)[1:13])^2/(n-3)
var
```
```{r,warning=FALSE,message=FALSE}
##Comparison (c)

nls(lnp~a+b/(T-c),start=list(a=20,b=-5000,c=30),data=dat2)
nlssum<-summary(nls(lnp~a+b/(T-c),start=list(a=20,b=-5000,c=30),data=dat2))
nlssum$coefficients[,1]                   ###nls a,b,c
nlssum$sigma^2			          ###nls variation

gauss<-c(af[100] ,bf[100],cf[100],var)
nlss<-c(nlssum$coefficients[,1],nlssum$sigma^2)
compare<-cbind(gauss,nlss)
rownames(compare)<-c("a","b","c","var")
compare                                   ###comparision table
```
```{r,warning=FALSE,message=FALSE}
##Steam Table (d)

Tcel<-seq(0,370,by=10)
Tk<-Tcel+273.15
p<-exp(af[100]+bf[100]/(Tk-cf[100]))

steam<-cbind(Tk,Tcel,p)                         ###steam table
steam
qplot(p,Tk)
qplot(log(p),Tk)
```