---
title: "Homework#7-Part3"
author: "Hye Yun Oh"
date: "2018³â 5¿ù 6ÀÏ"
output: html_document
---


```{r,warning=FALSE,message=FALSE}
#Part3 : Mark Recapture

##library

library(readxl)
library(tidyverse)
library(ggplot2)

##data manipulation

dat3<-read_excel("C:\\Users\\user\\Desktop\\APT-Antoine-Mark-Recapture data (2).xlsx",sheet=3)
dat3<-dat3[-c(38:39),-c(2:3)]
colnames(dat3)<-c("sex","days","x","y")
dat3<-mutate(dat3,t=as.numeric(days)/365.25)

##non-linear model estimation(a)

nls1<-nls(y~a-(a-x)*exp(-b*t),start=list(a=250,b=0.5),data=dat3)
summary(nls1)
Linfinite<-summary(nls1)$coefficients[1]
k<-summary(nls1)$coefficients[2]
```
```{r,warning=FALSE,message=FALSE}
##L plot (b)

t0<-(log((Linfinite-51.5)/Linfinite))/k
t0        ### at birth
L<-Linfinite*(1-exp(-k*(dat3$t-t0)))
dat3_both<-cbind(dat3,L)

ggplot(data=dat3_both,aes(x=t,y=L))+geom_line()
```
```{r,warning=FALSE,message=FALSE}
##L plot of male and female (c)
dat3_m<-dat3%>%filter(sex=="M")
dat3_f<-dat3%>%filter(sex=="F")
head(dat3_m)
head(dat3_f)

###male

nls2<-nls(y~a-(a-x)*exp(-b*t),start=list(a=230,b=0.1),data=dat3_m)
summary(nls2)
Linfinite_m<-summary(nls2)$coefficients[1]
k_m<-summary(nls2)$coefficients[2]
t0_m<-(log((Linfinite_m-51.5)/Linfinite_m))/k_m
t0_m        
L_m<-Linfinite_m*(1-exp(-k_m*(dat3_m$t-t0_m)))

###female

nls3<-nls(y~a-(a-x)*exp(-b*t),start=list(a=230,b=0.1),data=dat3_f)
summary(nls3)
Linfinite_f<-summary(nls3)$coefficients[1]
k_f<-summary(nls3)$coefficients[2]
t0_f<-(log((Linfinite_f-51.5)/Linfinite_f))/k_f
t0_f       
L_f<-Linfinite_f*(1-exp(-k_f*(dat3_f$t-t0_f)))

dat3_both_fm<-cbind(dat3,"Lboth"=c(L_f,L_m,0))
ggplot(data=dat3_both_fm,aes(x=t,y=Lboth,colour=sex))+geom_line()

```
